### ISSUE TITLE
EOFError: not enough bytes to read

### ISSUE THREAD

**Issue by Prc-PY** [joseph-fox/python-bloomfilter#36]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home/galeliu/.local/lib/python3.6/site-packages/pybloom_live/pybloom.py", line 368, in fromfile
    filter.filters.append(BloomFilter.fromfile(f, fl))
  File "/data/home/galeliu/.local/lib/python3.6/site-packages/pybloom_live/pybloom.py", line 212, in fromfile
    else filter.bitarray.fromfile(f, n - headerlen))
EOFError: not enough bytes to read

**Comment by joseph-fox** [comment]
@Prc-PY  can you help to fix it?

**Comment by joseph-fox** [comment]
Close it as no replies received.
